# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0376cbb2b16c5a06edb804af76cded0ff94846a43535fa33ed212229753afc7405391bd9e2b0b42aae7e1d4ffec106f402e3a411db2b7fec1f0dc767a6e82e02

test:
  secret_key_base: ba5895a2b26efbfa5eb897b145ce0ab2decf204e3d788c49041117145b0d1ddc794b2f9c33abb77c45274fb633e3a3b384ffc979774ef9ace4c110a604ee1e01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
